name: Notify Assigned Users

on:
  issues:
    types:
      - assigned # 이슈가 특정 사용자에게 할당될 때 실행
  issue_comment:
    types:
      - created # 할당된 이슈에 댓글이 달릴 때 실행

jobs:
  notify_users:
    runs-on: ubuntu-latest
    steps:
      - name: Notify All Assigned Users
        env:
          DISCORD_WEBHOOK_JKH: ${{ secrets.DISCORD_WEBHOOK_JKH }}
          DISCORD_WEBHOOK_KSJ: ${{ secrets.DISCORD_WEBHOOK_KSJ }}
          DISCORD_WEBHOOK_KYR: ${{ secrets.DISCORD_WEBHOOK_KYR }}
          DISCORD_WEBHOOK_LBM: ${{ secrets.DISCORD_WEBHOOK_LBM }}
          DISCORD_WEBHOOK_SIM: ${{ secrets.DISCORD_WEBHOOK_SIM }}
        run: |
          # Determine the event type (issues or issue_comment)
          EVENT_TYPE="${{ github.event_name }}"
          ASSIGNEES=""

          if [ "$EVENT_TYPE" = "issues" ]; then
            # Handle assigned event
            ASSIGNEES=$(echo '${{ toJson(github.event.issue.assignees) }}' | jq -r '.[].login')
            MESSAGE="이슈에 님 할당됨 보슈: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
          elif [ "$EVENT_TYPE" = "issue_comment" ]; then
            # Handle issue_comment event
            ASSIGNEES=$(echo '${{ toJson(github.event.issue.assignees) }}' | jq -r '.[].login')
            COMMENTER="${{ github.event.comment.user.login }}"
            MESSAGE="님 이슈에 댓글 달림 ㅇㅇ $COMMENTER: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}#issuecomment-${{ github.event.comment.id }}"
          else
            echo "Unsupported event type: $EVENT_TYPE"
            exit 1
          fi

          # Loop through all assignees
          for ASSIGNEE in $ASSIGNEES; do
            if [ "$ASSIGNEE" = "jdaily00" ]; then
              WEBHOOK_URL=$DISCORD_WEBHOOK_JKH
            elif [ "$ASSIGNEE" = "S2ej1n" ]; then
              WEBHOOK_URL=$DISCORD_WEBHOOK_KSJ
            elif [ "$ASSIGNEE" = "yoorym-kim" ]; then
              WEBHOOK_URL=$DISCORD_WEBHOOK_KYR
            elif [ "$ASSIGNEE" = "happygirlll" ]; then
              WEBHOOK_URL=$DISCORD_WEBHOOK_LBM
            elif [ "$ASSIGNEE" = "Saaad9" ]; then
              WEBHOOK_URL=$DISCORD_WEBHOOK_SIM
            else
              echo "No webhook configured for this assignee: $ASSIGNEE"
              continue
            fi

            # Send the notification via Discord Webhook
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"content\": \"$MESSAGE\"}" \
              $WEBHOOK_URL
          done
